apiVersion: v1
data:
  COMPOSE_PROJECT_NAME: superset
  CYPRESS_CONFIG: "false"
  DATABASE_DB: superset
  DATABASE_DIALECT: postgresql
  DATABASE_HOST: db
  DATABASE_PASSWORD: superset
  DATABASE_PORT: "5432"
  DATABASE_USER: superset
  FLASK_ENV: development
  POSTGRES_DB: superset
  POSTGRES_PASSWORD: superset
  POSTGRES_USER: superset
  PYTHONPATH: /app/pythonpath:/app/docker/pythonpath_dev
  REDIS_HOST: redis
  REDIS_PORT: "6379"
  SUPERSET_ENV: development
  SUPERSET_LOAD_EXAMPLES: yes
  SUPERSET_PORT: "8088"
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: db-docker--env
  name: docker--env
