apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Customers\Commit\Kompose\kompose.exe convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: superset-websocket
  name: superset-websocket
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    io.kompose.service: superset-websocket
status:
  loadBalancer: {}
